### ISSUE TITLE
TODO: add mp_infinite_ammo support

### ISSUE THREAD

**Issue by Giferns** [Giferns/HealthNade#19]

**Comment by shelydiviy** [comment]
Thx

**Comment by shelydiviy** [comment]
if (get_cvar_num("mp_infinite_ammo") == 2)	{
		new iWeaponInfiniteIds = get_member(id, m_iWeaponInfiniteIds);
		set_member(id, m_iWeaponInfiniteIds, iWeaponInfiniteIds > 0 ? (iWeaponInfiniteIds & ~(1<<_:WEAPON_NEW_ID)) : AllWeaponInfiniteIds & ~(1<<_:WEAPON_NEW_ID));
	}

**Comment by shelydiviy** [comment]
const AllWeaponInfiniteIds = ( (1<<_:WEAPON_SCOUT)|(1<<_:WEAPON_XM1014)|(1<<_:WEAPON_MAC10)|(1<<_:WEAPON_AUG)|(1<<_:WEAPON_UMP45)|(1<<_:WEAPON_SG550)|(1<<_:WEAPON_GALIL)|(1<<_:WEAPON_FAMAS)|(1<<_:WEAPON_AWP)|(1<<_:WEAPON_MP5N)|(1<<_:WEAPON_M249)|(1<<_:WEAPON_M3)|(1<<_:WEAPON_M4A1)|(1<<_:WEAPON_TMP)|(1<<_:WEAPON_G3SG1)|(1<<_:WEAPON_SG552)|(1<<_:WEAPON_AK47)|(1<<_:WEAPON_P90)|(1<<_:WEAPON_P228)|(1<<_:WEAPON_ELITE)|(1<<_:WEAPON_FIVESEVEN)|(1<<_:WEAPON_USP)|(1<<_:WEAPON_GLOCK18)|(1<<_:WEAPON_DEAGLE) );

**Comment by Giferns** [comment]
Done in https://github.com/Giferns/HealthNade/pull/22
